### ISSUE TITLE
Can't find Qt5DBus

### ISSUE THREAD

**Issue by exploshot** [qwertycoin-org/qwertycoin-zero#10]
### System Information

**Operating System**:  MacOS
**OS Version**:  10.14.3
**CPU Make, Model, & Speed**:  Ryzen 7
**Amount of RAM**:  16GB DDR4
**Hard Drive Type**:  SSD
**Hard Drive Size**:  80GB
**Volume Type**:  APFS

### Qwertycoin Build Information

**Version:**  1.1.4 Build 1114
**Binary Source:** 
**If self compiled, please provide all the build commands you used**
```
Please insert your build commands here. Example:

mkdir build && cd build
cmake -DBUILD_ALL:BOOL=TRUE ..
cmake --build . --config Release
```

**If self compiled, please provide of your Qwertycoin CMake output at the default verbosity**:
```
Explos-Mac:build exploshot$ cmake -DBUILD_ALL:BOOL=TRUE ..
-- CMake build type: Release
-- Found Git: /usr/bin/git (found version "2.20.1 (Apple Git-117)") 
-- Found Git: TRUE
-- Git tag: 1.1.4
-- Git commit ID: c505cad
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is AppleClang
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
-- CMAKE_HOST_SYSTEM_NAME: Darwin
-- CMAKE_SYSTEM_NAME: Darwin
-- CMAKE_SYSTEM_VERSION: 18.6.0
-- Detect OS targeted by the build: macos
-- Boost_DIR is not set. Using Hunter (package manager) to install Boost.
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: /Users/exploshot/.hunter
-- [hunter] [ Hunter-ID: f44b698 | Toolchain-ID: 7e73122 | Config-ID: 967ebfb ]
-- [hunter] BOOST_ROOT: /Users/exploshot/.hunter/_Base/f44b698/7e73122/967ebfb/Install (ver.: 1.69.0-p0)
-- [hunter] BOOST_ROOT: /Users/exploshot/.hunter/_Base/f44b698/7e73122/967ebfb/Install (ver.: 1.69.0-p0)
-- [hunter] BOOST_ROOT: /Users/exploshot/.hunter/_Base/f44b698/7e73122/967ebfb/Install (ver.: 1.69.0-p0)
-- [hunter] BOOST_ROOT: /Users/exploshot/.hunter/_Base/f44b698/7e73122/967ebfb/Install (ver.: 1.69.0-p0)
-- Boost  found.
-- Found Boost components:
   filesystem;program_options;system
-- Qt5_DIR is not set. Using Hunter (package manager) to install Qt5.
-- [hunter] QT_ROOT: /Users/exploshot/.hunter/_Base/f44b698/7e73122/967ebfb/Install (ver.: 5.11.3)
-- [hunter] QTCMAKEEXTRA_ROOT: /Users/exploshot/.hunter/_Base/f44b698/7e73122/967ebfb/Install (ver.: 1.0.34)
-- [hunter] QT_ROOT: /Users/exploshot/.hunter/_Base/f44b698/7e73122/967ebfb/Install (ver.: 5.11.3)
CMake Error at /Users/exploshot/.hunter/_Base/f44b698/7e73122/967ebfb/Install/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5DBus" with any
  of the following names:

    Qt5DBusConfig.cmake
    qt5dbus-config.cmake

  Add the installation prefix of "Qt5DBus" to CMAKE_PREFIX_PATH or set
  "Qt5DBus_DIR" to a directory containing one of the above files.  If
  "Qt5DBus" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  cmake/external/Qt5.cmake:20 (find_package)
  CMakeLists.txt:95 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/exploshot/Documents/GitHub/qwertycoin-zero/build/CMakeFiles/CMakeOutput.log".
See also "/Users/exploshot/Documents/GitHub/qwertycoin-zero/build/CMakeFiles/CMakeError.log".
```

### Issue Report

**Binary Reported:** 

#### Steps to Reproduce

1.  Download fresh Qwertycoin Zero source
2.  try to compile

**Comment by speqtr** [comment]
Try to reset cache by deleting `/Users/exploshot/.hunter/_Base/f44b698` or even `/Users/exploshot/.hunter`. This will remove all the previously built Hunter packages. At the moment build output looks like Hunter hits the cache installation, but can't find "Qt5DBus" package.

Another possible solution is to add `Qt5DBus` explicitely as a dependency to `Qt5_COMPONENTS` variable in `cmake/external/Qt5.cmake`.

@exploshot you could also open an issue about Qt5 faulty build in [Hunter repo](https://github.com/ruslo/hunter).

**Comment by speqtr** [comment]
@exploshot any updates? Did you try to reset Hunter's cache? I compiled latest version of Qwertycoin Zero multiple times and didn't get any errors.

**Comment by ghostx1x** [comment]
Hello guys - is it fixed with the missed qt files -  in the new version 1.2.0?

**Comment by speqtr** [comment]
@ghostx1x hi, at the moment Hunter's formula for Qt5 is still broken. So the only option to compile is to install pre-compiled Qt5 from https://qt.io, run `export Qt5_DIR=/path/to/qt/lib/cmake/Qt5` and then build `qwertycoin-zero` project.
